### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by robmackenzie** [vhs/raffle#3]
Ability to run under a non-privileged account
Ability to run on static files that are posted on each raffle
Output options that allow you to dump to static files (that can be imported above), to general text output, or even post directly to forum
A README
Bring back the .js version, and any other languages, so results can be corroborated.
Improve naming of various cryptographic variables inside. It’s a mess right now.
Functional tests
Cache user fetches. Currently runs slow as it calls each user for each item, could be sped up with a single decorator. Why haven’t I done this yet.

**Comment by robmackenzie** [comment]
Ability to run under a non-privileged account - Done
Output options that allow you to dump to static files (that can be imported above), to general text output, or even post directly to forum - Done and Done
Improve naming of various cryptographic variables inside. It’s a mess right now. - Done

Cache user fetches. Currently runs slow as it calls each user for each item, could be sped up with a single decorator. Why haven’t I done this yet. - Cached what I could. Calls to API further are in unsupported land of bypassing discourse lib and using unlisted API calls to backend.

Still Todo:
Functional tests
Docker files for local dev/running. 
A README
Bring back the .js version, and any other languages, so results can be corroborated. Ditto there used to be a BASH version.
Ability to run on static files that are posted on each raffle

**Comment by TyIsI** [comment]
Created specific issues to track various tasks/todos. Closing this issue as redundant.
