### ISSUE TITLE
feat: Separate winners from runner-ups with a collapsible arrow

### ISSUE THREAD

**Issue by JarrettR** [vhs/raffle#8]
When 1 item is won, it's unnecessary to immediately display the 22 runner-ups.  This causes additional confusion with particularly new members, only seeing their names on the list, without parsing how the system works.

Could be done with this Discourse syntax:

```
1. This is a winner
2. This is another winner

[details="Runner-ups"]
3. This is a runner-up
4. This person is also not a winner
[/details]
```

![image](https://github.com/vhs/raffle/assets/6027644/1b2f150b-b769-4bc7-8689-cb57ff5d4cc9)

**Comment by TyIsI** [comment]
If the poll option is always `<digit> x`, this could be parsed automatically.
